image: "ubuntu:latest"

before_script:
    - apt-get update && apt-get install -y clang-format cmake
    - mkdir build && cmake -B ./build

lint:
    script:
        - find . -path ./build -prune -false -o -type f \( -name *.cpp -o -name *.h \) | xargs clang-format -style=llvm -dry-run
