image: "kokoberry/team-f:c11"

stages:
    - build
    - test

build:
    stage: build
    script:
        - cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H. -B./build -G "Unix Makefiles"
        - cmake --build ./build
    artifacts:
        expire_in: 10 mins
        paths:
            - build/

lint:
    stage: test
    dependencies: []
    script:
        - apt-get update && apt-get install -y clang-format
        - find . -path ./build -prune -false -o -type f \( -name *.cpp -o -name *.h \) | xargs clang-format -style=llvm -dry-run -Werror

test:
    stage: test
    dependencies: 
        - build
    script:
        - ./build/bin/runAllTests
