image: "kokoberry/team-f:latest"

stages:
    - build
    - test

build:
    stage: build
    script:
        - cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H. -B./build -G "Unix Makefiles"
        - cmake --build ./build
    artifacts:
        expire_in: 10 mins
        paths:
            - build/

test:
    stage: test
    dependencies: 
        - build
    script:
        - ./build/bin/runAllTests
